version: "3.9"

services:
  frontend:
    image: jupyter/scipy-notebook: 2023-02-28
    ports: 
      - "10200:8888" 
    netrworks:
      - fromt-tier
      - back-tier
    environment:
      - JUPYTER_TOKEN = 123

  backend:
    image: mongo:latest
    ports: 
      - "27017:27017" 
    volumes:
      - db-data:/data/db1  
    networks:
      - back-tier


volumes:
  db-data:


networks:
  front-tier: {}
  back-tier: {}
  
